using Microsoft.EntityFrameworkCore;

namespace Asp_Group_Project.Data
{
    public enum DatabaseProvider
    {
        Sqlite,
        SqlServer,
        Postgres
    }

    public static class DatabaseInitializer
    {
        public static async Task EnsureDatabasesAsync(
            ApplicationDbContext identityContext,
            CommentContext commentContext,
            OrderHistoryContext orderHistoryContext,
            DatabaseProvider databaseProvider)
        {
            if (databaseProvider == DatabaseProvider.Sqlite)
            {
                await identityContext.Database.EnsureCreatedAsync();
                await commentContext.Database.EnsureCreatedAsync();
                await orderHistoryContext.Database.EnsureCreatedAsync();
                return;
            }

            if (databaseProvider == DatabaseProvider.Postgres)
            {
                await EnsurePostgresIdentitySchemaAsync(identityContext);
                await EnsurePostgresAppTablesAsync(commentContext, orderHistoryContext);
            }
        }

        private static async Task EnsurePostgresIdentitySchemaAsync(ApplicationDbContext identityContext)
        {
            if (!await HasPostgresTableAsync(identityContext, "AspNetUsers"))
            {
                await identityContext.Database.ExecuteSqlRawAsync(identityContext.Database.GenerateCreateScript());
            }
        }

        private static async Task EnsurePostgresAppTablesAsync(
            CommentContext commentContext,
            OrderHistoryContext orderHistoryContext)
        {
            await commentContext.Database.ExecuteSqlRawAsync("""
                CREATE TABLE IF NOT EXISTS "Comments" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "productId" integer NOT NULL,
                    "Rating" integer NULL,
                    "Title" text NULL,
                    "Author" text NULL,
                    "Body" text NULL
                );
                """);

            await orderHistoryContext.Database.ExecuteSqlRawAsync("""
                CREATE TABLE IF NOT EXISTS "OrderHistory" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "Username" text NOT NULL,
                    "FullName" text NOT NULL,
                    "Address" text NOT NULL,
                    "Date" timestamp with time zone NOT NULL,
                    "ProductId" integer NOT NULL,
                    "Quantity" integer NOT NULL
                );
                """);
        }

        private static async Task<bool> HasPostgresTableAsync(DbContext context, string tableName)
        {
            var connection = context.Database.GetDbConnection();
            if (connection.State != System.Data.ConnectionState.Open)
            {
                await connection.OpenAsync();
            }

            await using var command = connection.CreateCommand();
            command.CommandText = """
                SELECT EXISTS (
                    SELECT 1
                    FROM information_schema.tables
                    WHERE table_schema = 'public'
                    AND table_name = @tableName
                );
                """;

            var parameter = command.CreateParameter();
            parameter.ParameterName = "tableName";
            parameter.Value = tableName;
            command.Parameters.Add(parameter);

            return (bool)(await command.ExecuteScalarAsync() ?? false);
        }
    }
}
